FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml poetry.lock* ./

RUN pip install --no-cache-dir poetry \
 && poetry config virtualenvs.create false \
 && poetry install --no-root --no-interaction --no-ansi

COPY app ./app

ENV PYTHONPATH=/app

EXPOSE 5000

CMD ["python", "-m", "app.app"]
