server {
    listen 80;
    server_name _;

    # ----------------
    # Healthcheck
    # ----------------
    location = /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    # ----------------
    # CORS (QA)
    # ----------------
    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;

    if ($request_method = OPTIONS) {
        return 204;
    }

    # ========================
    # USERS
    # ========================

    location /api/v1/users/auth/login {
        proxy_pass http://user-login-service:5000/auth/login;
        include /etc/nginx/proxy_params;
    }

    location /api/v1/users/auth/logout {
        proxy_pass http://user-logout-service:5000/api/v1/logout;
        include /etc/nginx/proxy_params;
    }

    location /api/v1/users/profiles/ {
        proxy_pass http://user-profile-service:5000/profiles/;
        include /etc/nginx/proxy_params;
    }

    location /api/v1/users/roles {
        proxy_pass http://user-role-service:5000/roles;
        include /etc/nginx/proxy_params;
    }

    location /api/v1/users/verification {
        proxy_pass http://user-verification-service:5000;
        include /etc/nginx/proxy_params;
    }

    # ========================
    # ACADEMIC
    # ========================

    location /api/v1/academic/students/ {
        proxy_pass http://student-profile-service:5000/students/;
        include /etc/nginx/proxy_params;
    }

    # ========================
    # COMMUNITY
    # ========================

    location /api/v1/community/programs {
        proxy_pass http://community-programs-service:5000/community-programs;
        include /etc/nginx/proxy_params;
    }

    location /api/v1/community/hours {
        proxy_pass http://community-hours-service:5000/community-hours;
        include /etc/nginx/proxy_params;
    }

    # ========================
    # INTERNSHIPS
    # ========================

    location /api/v1/internships/offers {
        proxy_pass http://internships-offers-service:5000/internships-offers;
        include /etc/nginx/proxy_params;
    }

    location /api/v1/internships/hours {
        proxy_pass http://internships-hours-service:5000/internships-hours;
        include /etc/nginx/proxy_params;
    }

    # ========================
    # LANGUAGES
    # ========================

    location /api/v1/languages/english/courses {
        proxy_pass http://english-courses-service:5000/english-courses;
        include /etc/nginx/proxy_params;
    }

    location /api/v1/languages/english/level {
        proxy_pass http://english-level-service:5000/english-level;
        include /etc/nginx/proxy_params;
    }
}
