[tool.poetry]
name = "financial-clearance-service"
version = "0.1.0"
description = "Financial clearance validation service"
authors = ["Rommel Pachacama"]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.0"
psycopg2-binary = "^2.9.9"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
